export enum Screens {
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN UP',
  AUTH_HOME = 'AUTH_HOME',
  LIBRARY_STACK = 'LIBRARY_STACK',
  CATEGORY = 'CATEGORY',
  LIBRARY = 'LIBRARY',
  MEDIA_PLAYER = 'MEDIA_PLAYER',
}
